### ISSUE TITLE
Use This Issue for the thread of your Queries.

### ISSUE THREAD

**Issue by vijaygupta18** [vijaygupta18/Hacktoberfest-2021#123]
Write your queries here.
I'll try my best to Help you.

**Comment by Mr-vabs** [comment]
Please accept my PR

**Comment by Padmanabh82** [comment]
i have made a pr on https://github.com/Padmanabh82/Hacktoberfest-2021.git but my project has added as submodule how i don't know. will it work ??/ and also accept my pr

**Comment by vijaygupta18** [comment]
> i have made a pr on https://github.com/Padmanabh82/Hacktoberfest-2021.git but my project has added as submodule how i don't know. will it work ??/ and also accept my pr

Delete your repo and fork again..and add your projects..let me know if you get any problem.

**Comment by Padmanabh82** [comment]
> > i have made a pr on https://github.com/Padmanabh82/Hacktoberfest-2021.git but my project has added as submodule how i don't know. will it work ??/ and also accept my pr
> 
> Delete your repo and fork again..and add your projects..let me know if you get any problem.

sir i don't know but it does't accpt folder to uplode. when i use git it made a submodule

**Comment by vijaygupta18** [comment]
> > > i have made a pr on https://github.com/Padmanabh82/Hacktoberfest-2021.git but my project has added as submodule how i don't know. will it work ??/ and also accept my pr
> > 
> > 
> > Delete your repo and fork again..and add your projects..let me know if you get any problem.
> 
> sir i don't know but it does't accpt folder to uplode. when i use git it made a submodule

well for now try uploading files through GitHub site and generate pr from here .

**Comment by vijaygupta18** [comment]
> Please accept my PR

done

**Comment by Padmanabh82** [comment]
> > Please accept my PR
> 
> done

thanks

**Comment by Padmanabh82** [comment]
> > > > i have made a pr on https://github.com/Padmanabh82/Hacktoberfest-2021.git but my project has added as submodule how i don't know. will it work ??/ and also accept my pr
> > > 
> > > 
> > > Delete your repo and fork again..and add your projects..let me know if you get any problem.
> > 
> > sir i don't know but it does't accpt folder to uplode. when i use git it made a submodule
> 
> well for now try uploading files through GitHub site and generate pr from here .

Sir when I upload from web it doesn't accept folder only accept file but my project is in react

**Comment by Padmanabh82** [comment]
My project :- https://github.com/Padmanabh82/TextUtils-React

**Comment by Padmanabh82** [comment]
I will try from my mobile

**Comment by Padmanabh82** [comment]
I cannot upload folders

**Comment by Padmanabh82** [comment]
Only file

**Comment by Padmanabh82** [comment]
What to do sir ??

**Comment by harshvardhan56** [comment]
accept my PR #133 
i am beginner in this can you please check that this is created or not..

**Comment by vijaygupta18** [comment]
> accept my PR #133 i am beginner in this can you please check that this is created or not..

done

**Comment by vijaygupta18** [comment]
> I cannot upload folders

well the try to methods that i have mentioned in readme section. You can upload folder by Drag and drop method.Google it for more info.

**Comment by Padmanabh82** [comment]
> > I cannot upload folders
> 
> well the try to methods that i have mentioned in readme section. You can upload folder by Drag and drop method.Google it for more info.

sir i have made a pull request with anther project:- https://github.com/TAbhay/Hactoberfest-2021/pull/446

it is working. please accept it

**Comment by vijaygupta18** [comment]
> > > I cannot upload folders
> > 
> > 
> > well the try to methods that i have mentioned in readme section. You can upload folder by Drag and drop method.Google it for more info.
> 
> sir i have made a pull request with anther project:- [TAbhay/Hactoberfest-2021#446](https://github.com/TAbhay/Hactoberfest-2021/pull/446)
> 
> it is working. please accept it

that's not my repo. It's owned by someone else.Create a pr on my repo I'll Merge it.

**Comment by Padmanabh82** [comment]
> > > > I cannot upload folders
> > > 
> > > 
> > > well the try to methods that i have mentioned in readme section. You can upload folder by Drag and drop method.Google it for more info.
> > 
> > 
> > sir i have made a pull request with anther project:- [TAbhay/Hactoberfest-2021#446](https://github.com/TAbhay/Hactoberfest-2021/pull/446)
> > it is working. please accept it
> 
> that's not my repo. It's owned by someone else.Create a pr on my repo I'll Merge it.
please accept:- https://github.com/vijaygupta18/Hacktoberfest-2021/pull/134
and issue was of other repo

**Comment by vijaygupta18** [comment]
> > > > > I cannot upload folders
> > > > 
> > > > 
> > > > well the try to methods that i have mentioned in readme section. You can upload folder by Drag and drop method.Google it for more info.
> > > 
> > > 
> > > sir i have made a pull request with anther project:- [TAbhay/Hactoberfest-2021#446](https://github.com/TAbhay/Hactoberfest-2021/pull/446)
> > > it is working. please accept it
> > 
> > 
> > that's not my repo. It's owned by someone else.Create a pr on my repo I'll Merge it.
> > please accept:- #134
> > and issue was also of other repo

done

**Comment by Padmanabh82** [comment]
> > > > > > I cannot upload folders
> > > > > 
> > > > > 
> > > > > well the try to methods that i have mentioned in readme section. You can upload folder by Drag and drop method.Google it for more info.
> > > > 
> > > > 
> > > > sir i have made a pull request with anther project:- [TAbhay/Hactoberfest-2021#446](https://github.com/TAbhay/Hactoberfest-2021/pull/446)
> > > > it is working. please accept it
> > > 
> > > 
> > > that's not my repo. It's owned by someone else.Create a pr on my repo I'll Merge it.
> > > please accept:- #134
> > > and issue was also of other repo
> 
> done

now will counted in hactober fest ??

**Comment by Saumya2600** [comment]
Can you plese accept my pr in bubble sort , I've made the code much shorter and it works fine

**Comment by harshvardhan56** [comment]
please merge #149 . in this all the sorting algorithm is implemented in c

**Comment by Saumya2600** [comment]
@harshvardhan56  can you describe how to re merge it ? Also I made the code of heap sort.java lesser and also merged it

**Comment by vijaygupta18** [comment]
> please merge #149 . in this all the sorting algorithm is implemented in c

done

**Comment by vijaygupta18** [comment]
> If you have merged then why can't I see any progress on Hacktoberfest page ;)
try reloading the page..or create pr again I'll approve it

**Comment by Saumya2600** [comment]
I'll create pr again as reloading the page still shows my status as 0 in progress

**Comment by vijaygupta18** [comment]
> I'll create pr again as reloading the page still shows my status as 0 in progress

okay do it... avoid any conflicts

**Comment by Saumya2600** [comment]
Even after you have merged my progress still shows 0 , I don't know what to do smh .

**Comment by vijaygupta18** [comment]
> Even after you have merged my progress still shows 0, I don't know what to do smh.

it's a server error..wait for some time it will get updated

**Comment by pranavsuryadevara** [comment]
Please accept my PR.

**Comment by Eswari-Priya** [comment]
In order to make a contribution, first i should create an issue ,work on it and then raise a pr? Is that it ? Or can i directly raise a pr without creating issue?

**Comment by harshvardhan56** [comment]
in my PR contribution it's showing that hacktoberfest accepted 
but matures in 14 days?
what does it mean?

**Comment by vijaygupta18** [comment]
> in my PR contribution it's showing that hacktoberfest accepted but matures in 14 days? what does it mean?

this means your pr will be verified by the e community after 14 days.

**Comment by harshvardhan56** [comment]
what are the chances of acceptances?
i have just contributed in dsa (c++)

**Comment by vijaygupta18** [comment]
> what are the chances of acceptances? i have just contributed in dsa (c++)

if get merged in hacktober-accepted repo then valid.

**Comment by krishnavpai** [comment]
> > what are the chances of acceptances? i have just contributed in dsa (c++)
> 
> if get merged in hacktober-accepted repo then valid.

Firstly Thank you @vijaygupta18 for accepting my PR.
But it seems that there is a lot of spam happening everywhere and many repositories are getting the message "Excluded from project".

**Comment by Padmanabh82** [comment]
> > Even after you have merged my progress still shows 0, I don't know what to do smh.
> 
> it's a server error..wait for some time it will get updated

Ya it takes much time to load

**Comment by nishantkumar1308** [comment]
I would like to create a Dyanamic Programming folder using C++. Can in  start working on it.

**Comment by vijaygupta18** [comment]
> I would like to create a Dyanamic Programming folder using C++. Can in start working on it.

sure

**Comment by vijaygupta18** [comment]
> > > what are the chances of acceptances? i have just contributed in dsa (c++)
> > 
> > 
> > if get merged in hacktober-accepted repo then valid.
> 
> Firstly Thank you @vijaygupta18 for accepting my PR. But it seems that there is a lot of spam happening everywhere and many repositories are getting the message "Excluded from project".

Yeah.That's why i am merging only valid prs

**Comment by Adarsh-Saurabh** [comment]
I got hactoberfest batch in some repositories but those got removed as excluded project.

**Comment by aastha01chauhan** [comment]
Key Pad Problem [Asked in FAANG Interview] I would like to make a folder for mostly frequently asked interview problems. Can I start working on it? I am beginner please let me know if I can contribute.

**Comment by HiruniPerera** [comment]
hello I would love to contribute to this by uploading a web application I have developed. Can I contribute?

**Comment by vijaygupta18** [comment]
> hello I would love to contribute to this by uploading a web application I have developed. Can I contribute?

yeah sure.

**Comment by vijaygupta18** [comment]
> Key Pad Problem [Asked in FAANG Interview] I would like to make a folder for mostly frequently asked interview problems. Can I start working on it? I am beginner please let me know if I can contribute.

yeah sure...do pr

**Comment by drishyadamodaran** [comment]
@vijaygupta18  Kindly give hacktoberfest label to my pr #44

**Comment by vijaygupta18** [comment]
@drishyadamodaran  done!

**Comment by nishantkumar1308** [comment]
@vijaygupta18  Kindly give hactoberfest label on my pr #210

**Comment by Saumya2600** [comment]
@vijaygupta18  Kindly give hacktoberfest label on my pr #167 and #171 please.

**Comment by vijaygupta18** [comment]
> @vijaygupta18 Kindly give hactoberfest label on my pr #210

done!

**Comment by vijaygupta18** [comment]
@Saumya2600  done!

**Comment by SrirajBehera** [comment]
my PR is #294 . i am new to hacktoberfest. what to do next?

**Comment by vijaygupta18** [comment]
> my PR is #294 . i am new to hacktoberfest. what to do next?

i have merged your pr..wait for your pr to get matured

**Comment by vijaygupta18** [comment]
> Kindly give hacktoberfest label to my pr #422

done

**Comment by parvsharmaa** [comment]
Hey, @vijaygupta18 please review pr #493 and Kindly give it hacktoberfest label :) 

#hacktoberfest2021

**Comment by parvsharmaa** [comment]
#493
